remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Krótki opis projektu, którym się obecnie zajmuję]
description: [Our goal is to create a clone of the classic game of rock, paper, scissors. This world-class production will change the lives of many users.
