title: [Krótki opis projektu, którym się obecnie zajmuję]
description: [Our goal is to create a clone of the classic game of rock, paper, scissors. This world-class production will change the lives of many users.

